# Generated by Django 5.1.1 on 2024-12-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_created_at_order_status_orderitems_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_signeture',
            new_name='payment_signature',
        ),
    ]
